/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RegulationRole;

import Business.BRTSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BusOrganization;
import Business.Organization.RegulationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DispatchBusWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jianing Wang
 */
public class RegulationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegulatorWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private RegulationOrganization regulationOrganization;
    private UserAccount userAccount;
    private BRTSystem system;
    
    public RegulationWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,
            RegulationOrganization organization, BRTSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.regulationOrganization = (RegulationOrganization) organization;
        this.system = system;

        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();
        model.setRowCount(0);
        
        for (WorkRequest workRequest : regulationOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            DispatchBusWorkRequest request = (DispatchBusWorkRequest) workRequest;
            row[0] = request;
            row[1] = request.getReceiver()== null ? null : request.getReceiver().getEmployee().getName();
            row[2] = request.getSender().getEmployee().getName();
            row[3] = request.getStatus();
            row[4] = request.getTestResult();
            row[5] = request.getMessage();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assginJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setText("My Work Area - Regulation Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 114, -1, -1));

        assginJButton.setText("Assign to me");
        assginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assginJButtonActionPerformed(evt);
            }
        });
        add(assginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 406, -1, -1));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 463, 185, -1));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Platform", "Receiver", "Sender", "Status", "Result", "Notice"
            }
        ));
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 245, 768, 133));
    }// </editor-fold>//GEN-END:initComponents

    private void assginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assginJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first");
        }
        
        WorkRequest workRequest = (WorkRequest)requestJTable.getValueAt(selectedRow, 0);
        workRequest.setReceiver(userAccount);
        workRequest.setStatus("Pending");
        
        populateRequestTable();
    }//GEN-LAST:event_assginJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        DispatchBusWorkRequest request = (DispatchBusWorkRequest) requestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ProcessDispatchRequestJPanel panel = new ProcessDispatchRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessDispatchRequestJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assginJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable requestJTable;
    // End of variables declaration//GEN-END:variables
}
