/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LineRole;

import Business.Organization.PlatformOrganization;
import Business.Platform.Platform;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jianing Wang
 */
public class AddPlatformJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPlatformJPanel
     */
    
    private JPanel userProcessContainer;
    private PlatformOrganization platformOrganization;
    
    public AddPlatformJPanel(JPanel userProcessContainer, PlatformOrganization platformOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.platformOrganization = platformOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        platformNameJTextField = new javax.swing.JTextField();
        platformIDJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addPlatformJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setText("Add Platform");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 143, -1, -1));

        jLabel2.setText("Platform Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 246, -1, -1));

        jLabel3.setText("Platform ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 313, -1, -1));
        add(platformNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 243, 210, -1));
        add(platformIDJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 310, 210, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 531, -1, -1));

        addPlatformJButton.setText("Add");
        addPlatformJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatformJButtonActionPerformed(evt);
            }
        });
        add(addPlatformJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 377, 135, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addPlatformJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatformJButtonActionPerformed
        // TODO add your handling code here:
        Platform platform = new Platform();
        platform.setName(platformNameJTextField.getText());
        int platformID = 0;
        try {
            platform.setPlatformID(Integer.parseInt(platformIDJTextField.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid PlatformID", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
               
        if (platformOrganization.getEmployeeDirectory().getEmployeeList().contains(platform)){
            JOptionPane.showMessageDialog(null, "This line had been added before", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            platformOrganization.getEmployeeDirectory().getEmployeeList().add(platform);
        }
        JOptionPane.showMessageDialog(null, "Success", "Good Job~!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addPlatformJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlatformJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField platformIDJTextField;
    private javax.swing.JTextField platformNameJTextField;
    // End of variables declaration//GEN-END:variables
}
