/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LineRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Line.Line;
import Business.Organization.LineOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Line;
import Business.Organization.PlatformOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Jianing Wang
 */
public class LineWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LineManagementWorkArea
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private LineOrganization lineOrganization;
    private Enterprise enterprise;
       
    public LineWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, 
            LineOrganization lineOrganization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.lineOrganization = lineOrganization;
        this.enterprise = enterprise;
        
        enterpriseValueLabel.setText(enterprise.getName());
        lineValueLabel.setText(lineOrganization.getName());
        
        popoulatePlatformOrgComboBox();
    }

    public void popoulatePlatformOrgComboBox() {
        platformOrganizationJComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof PlatformOrganization) {
                platformOrganizationJComboBox.addItem(organization);
            }
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseValueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        platformOrganizationJComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        addPlatformButton = new javax.swing.JButton();
        mngPlatformJButton = new javax.swing.JButton();
        lineValueLabel = new javax.swing.JLabel();
        sendRequestJButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setText("My Work Area - Line  Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 111, -1, -1));

        jLabel2.setText("Enterprise:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 184, -1, -1));

        enterpriseValueLabel.setText("<value>");
        add(enterpriseValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 184, 130, -1));

        jLabel3.setText("Line:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 245, -1, -1));

        platformOrganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(platformOrganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 307, 290, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 306, 304, -1));

        addPlatformButton.setText("Add Platform");
        addPlatformButton.setEnabled(false);
        addPlatformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatformButtonActionPerformed(evt);
            }
        });
        add(addPlatformButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 375, -1, 93));

        mngPlatformJButton.setText("Manage Platform");
        mngPlatformJButton.setEnabled(false);
        mngPlatformJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngPlatformJButtonActionPerformed(evt);
            }
        });
        add(mngPlatformJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 375, -1, 93));

        lineValueLabel.setText("<value>");
        add(lineValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 245, -1, -1));

        sendRequestJButton.setText("Send Request");
        sendRequestJButton.setEnabled(false);
        sendRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestJButtonActionPerformed(evt);
            }
        });
        add(sendRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 375, -1, 92));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        if (platformOrganizationJComboBox.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "YOU don't have a platform organization yet.");
            return;
        } else {
            addPlatformButton.setEnabled(true);
            mngPlatformJButton.setEnabled(true);
            sendRequestJButton.setEnabled(true);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void addPlatformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatformButtonActionPerformed
        // TODO add your handling code here:
        PlatformOrganization platformOrganization = (PlatformOrganization) platformOrganizationJComboBox.getSelectedItem();
        AddPlatformJPanel panel = new AddPlatformJPanel(userProcessContainer, platformOrganization);
        userProcessContainer.add("AddPlatformJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_addPlatformButtonActionPerformed

    private void mngPlatformJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngPlatformJButtonActionPerformed
        // TODO add your handling code here:
        PlatformOrganization platformOrganization = (PlatformOrganization) platformOrganizationJComboBox.getSelectedItem();
        ManagePlatformJPanel panel = new ManagePlatformJPanel(userProcessContainer, userAccount, platformOrganization, enterprise);
        userProcessContainer.add("ManagePlatformJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_mngPlatformJButtonActionPerformed

    private void sendRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestJButtonActionPerformed
        // TODO add your handling code here:
        PlatformOrganization platformOrganization = (PlatformOrganization) platformOrganizationJComboBox.getSelectedItem();
        SendRequestJPanel panel = new SendRequestJPanel(userProcessContainer, userAccount, platformOrganization, enterprise);
        userProcessContainer.add("SendRequestJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_sendRequestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlatformButton;
    private javax.swing.JLabel enterpriseValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lineValueLabel;
    private javax.swing.JButton mngPlatformJButton;
    private javax.swing.JComboBox platformOrganizationJComboBox;
    private javax.swing.JButton sendRequestJButton;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
