/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LineRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PlatformOrganization;
import Business.Organization.RegulationOrganization;
import Business.Platform.Platform;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DispatchBusWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jianing Wang
 */
public class SendRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageLineJPanel
     */
    
    private JPanel userProcessContainer;
    private PlatformOrganization platformOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    public SendRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, 
            PlatformOrganization platformOrganization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.platformOrganization = platformOrganization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        populateVolumnTable();
        populateRequestTable();
    }
    
    public void populateVolumnTable() {
        DefaultTableModel dtm = (DefaultTableModel) volumnJTable.getModel();
        dtm.setRowCount(0);

        for (Employee employee : platformOrganization.getEmployeeDirectory().getEmployeeList()) {
            if (employee instanceof Platform) {
                Platform platform = (Platform) employee;
                Object row[] = new Object[2];

                row[0] = platform;
                row[1] = platform.getVolumn();

                dtm.addRow(row);
            }

        }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();        
        model.setRowCount(0);
        
        for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            DispatchBusWorkRequest request = (DispatchBusWorkRequest) workRequest;
            row[0] = ((Platform) request.getPlatform());
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((DispatchBusWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            row[4] = request.getRequestTime();
            row[5] = request.getResolveTime();
            
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volumnJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        requestJButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 531, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setText("Manage Line Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 96, -1, -1));

        volumnJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Platform Name", "Volumn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(volumnJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 183, 593, 139));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Platform", "Receiver", "Status", "Result", "Request Time", "Resolve Time"
            }
        ));
        jScrollPane2.setViewportView(requestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 350, 1148, 126));

        requestJButton.setText("Send Request");
        requestJButton.setMaximumSize(new java.awt.Dimension(129, 41));
        requestJButton.setMinimumSize(new java.awt.Dimension(129, 41));
        requestJButton.setPreferredSize(new java.awt.Dimension(129, 41));
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 183, 447, 139));
    }// </editor-fold>//GEN-END:initComponents

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        int selectedRow = volumnJTable.getSelectedRow();
        if (selectedRow >= 0) {
            Platform platform = (Platform) volumnJTable.getValueAt(selectedRow, 0);
            DispatchBusWorkRequest request = new DispatchBusWorkRequest();
            //request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setPlatform(platform);
            request.setRequestTime(date);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof RegulationOrganization) {
                    org = organization;
                    break;
                }
            }

            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                populateRequestTable();
            } else {
                JOptionPane.showMessageDialog(null, "You don't have a RegulationOrganization yet.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton requestJButton;
    private javax.swing.JTable requestJTable;
    private javax.swing.JTable volumnJTable;
    // End of variables declaration//GEN-END:variables
}
